#####################################
# Application
#####################################
spring.application.name=deal-pipeline-portal
server.port=8080


#####################################
# MongoDB Configuration
#####################################
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB_NAME:deal_pipeline_db}
spring.data.mongodb.auto-index-creation=true


#####################################
# JWT Configuration
#####################################
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:36000000}
# default = 1 hour


#####################################
# Spring Security
#####################################
logging.level.org.springframework.security=INFO


#####################################
# Actuator
#####################################
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


server.forward-headers-strategy=framework

